POST http://localhost:3000/campaigns

{
    "name": "Vinicius JR",
    "content": "change passwd",
    "emails": ["gabriel@teste.com","gabriel1@teste.com","gabriel2@teste.com"]
}

###
GET  http://localhost:3000/campaigns/d73lki8bgs4h2o2u2600

###
PATCH http://localhost:3000/campaigns/cancel/d73kcq0bgs4gg11vt270

###
DELETE  http://localhost:3000/campaigns/delete/d73llg0bgs4h2o2u2620